In [1]:
import pandas as pd
import os
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [7]:
iris_data = pd.read_csv("iris.csv")
print(iris_data.head())

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
iris_data['Species'] = label_encoder.fit_transform(iris_data['Species'])

np_iris =  iris_data.to_numpy()

X_data = np_iris[:,0:4]
Y_data = np_iris[:,4]


print("\nFeature before scaling: \n-------------")
print(X_data[:5,:])
print("\nTarget before scaling: \n--------------")
print(Y_data[:5])

scaler = StandardScaler().fit_transform(X_data)

X_data = scaler.transform(X_data)

Y_data = tf.keras.utils.to_categorical(Y_data,3)

X_train,X_test,Y_train,Y_test = train_test_split(X_data,Y_data,test_size=0.1)

print("\nTrain test dimensions:\n-----------------------------------")
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Feature before scaling: 
-------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target before scaling: 
--------------
[0. 0. 0. 0. 0.]


AttributeError: 'numpy.ndarray' object has no attribute 'transform'