In [1]:
import numpy as np

In [2]:
a = np.array([9.0,7.0,8.0])

In [13]:
x=np.empty(10)
x
print(type(x))
a.itemsize

<class 'numpy.ndarray'>


8

In [16]:
x.shape = (10,1)
x

array([[9.74573486e-312],
       [2.37151510e-322],
       [0.00000000e+000],
       [0.00000000e+000],
       [1.60219306e-306],
       [1.16095484e-028],
       [2.64672505e+180],
       [3.35282789e-110],
       [6.48224637e+170],
       [3.67145870e+228]])

In [17]:
z=np.linspace(2,5,50)
print(z)

[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]


In [18]:
np.random.seed(0)
z1=np.random.randint(11,size=10)
z1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [4]:
a=[1,4,5]
b=[5,6,7]
a@b

TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [6]:
a=np.array([1,4,5])
b=np.array([5,6,7])
a*b

array([ 5, 24, 35])

In [21]:
z=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype = 'float32')
print(z)

[[9. 8. 7.]
 [6. 5. 4.]]


In [22]:
z.ndim

2

In [23]:
z.shape

(2, 3)

In [24]:
# Get type
z.dtype

dtype('float32')

In [25]:
z.itemsize

4

In [26]:
a.nbytes

12

In [27]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [28]:
#get a specific element [r,c]k
a[1,5]

13

In [29]:
#Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [31]:
#gettin little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [32]:
a[1,5] = 20
a[:,2] = [5]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [33]:
#3-d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
b[:,1,0]

array([3, 7])

In [35]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [37]:
#random deciaml numbers
np.random.rand(4,2,7)

array([[[0.29753461, 0.05671298, 0.27265629, 0.47766512, 0.81216873,
         0.47997717, 0.3927848 ],
        [0.83607876, 0.33739616, 0.64817187, 0.36824154, 0.95715516,
         0.14035078, 0.87008726]],

       [[0.47360805, 0.80091075, 0.52047748, 0.67887953, 0.72063265,
         0.58201979, 0.53737323],
        [0.75861562, 0.10590761, 0.47360042, 0.18633234, 0.73691818,
         0.21655035, 0.13521817]],

       [[0.32414101, 0.14967487, 0.22232139, 0.38648898, 0.90259848,
         0.44994999, 0.61306346],
        [0.90234858, 0.09928035, 0.96980907, 0.65314004, 0.17090959,
         0.35815217, 0.75068614]],

       [[0.60783067, 0.32504723, 0.03842543, 0.63427406, 0.95894927,
         0.65279032, 0.63505887],
        [0.99529957, 0.58185033, 0.41436859, 0.4746975 , 0.6235101 ,
         0.33800761, 0.67475232]]])

In [38]:
np.random.randint(9,size=(3,3))

array([[0, 1, 5],
       [3, 0, 5],
       [0, 1, 2]])

In [39]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
arr=np.array([1,2,3])
r1=np.repeat(arr,4)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [46]:
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
arr_1 = np.array([[[1,1,1],
                  [3,3,3]],
                 [[2,2,2],
                  [4,4,4]],
                 [[5,5,5],
                  [6,6,6]]])
defnp.sum(arr_1,axis=1)

array([[ 4,  4,  4],
       [ 6,  6,  6],
       [11, 11, 11]])

In [28]:
import numpy as np
def mtr_crt(R,C):
    print('enter the entries in a single line (separated by space): ')
    entries=list(map(int,input().split()))
    matrix = np.array(entries).reshape(R,C)
    return matrix
mtr = mtr_crt(3,3)
print(mtr)
diag = np.diagonal(mtr)
print(np.diagonal(mtr))
r=diag[::-1]
print(r)
mtr[0][0]=5
print(mtr)

enter the entries in a single line (separated by space): 
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[9 5 1]
[[5 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x[0]=y[1]
x

array([5, 2, 3])

In [17]:
import math
a=np.array([0,0,0],dtype=float)
a[0]=5
a

array([5., 0., 0.])

In [37]:
import numpy
R=int(input('enter the number of rows'))
C=int(input('enter the number of columns'))
ele1=[int(input()) for i in range(R*3)]
ele2=[int(input()) for i in range(R*3)]
m1=np.array(ele1).reshape(R,C)
m2=np.array(ele2).reshape(R,C)
print(m1)
print(m2)


enter the number of rows3
enter the number of columns3
1
2
3
4
5
6
7
8
9
9
8
7
6
5
4
3
2
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [51]:
m1[:2,1:]=m2[1:,:2]
print(m2[1:,:2])
m1

[[6 5]
 [3 2]]


array([[1, 6, 5],
       [4, 3, 2],
       [7, 8, 9]])

In [2]:
guest_num=int(input('Guest number:'))
lst=[({int(input('room: ')):input('Name of guest:')},input('room of the guest who arrived next: ')) for i in range(guest_num)]
print(lst)


Guest number:2
room: 125
Name of guest:John
room of the guest who arrived next: 210
room: 157
Name of guest:Kanna
room of the guest who arrived next: 125
[({125: 'John'}, '210'), ({157: 'Kanna'}, '125')]


In [3]:
lst[0]

({125: 'John'}, '210')

In [4]:
lst[0][0]

{125: 'John'}

In [9]:
l=[[1,2,3],
 [4,5,6],
 [7,8,9]]
for i in range(1):
    l[i][i],l[i+1][i+1],l[i+2][i+2]=l[i+2][i+2],l[i+1][i+1],l[i][i]
for i in l:
    print(i)

[9, 2, 3]
[4, 5, 6]
[7, 8, 1]
